sudo: required
services:
- docker
language: python
python:
- '2.7'
install: pip install -e .
script:
- py.test test/unit/ -s -v
- py.test test/integration/test_logcontains.py -s -v --rule=test/integration/LOGCONTAINSFIXTURE.yaml
- py.test test/integration/test_nologcontains.py -s -v --rule=test/integration/NOLOGCONTAINSFIXTURE.yaml
- py.test test/integration/test_htmlcontains.py -s -v --rule=test/integration/HTMLCONTAINSFIXTURE.yaml
- py.test test/integration/test_http.py -s -v
- py.test test/integration/test_cookie.py -s -v --rule=test/integration/COOKIEFIXTURE.yaml
- py.test test/integration/test_multipart.py -s -v --rule=test/integration/MULTIPART.yaml
- py.test test/integration/test_expecterror.py -s -v --rule=test/integration/EXPECTERRORFIXTURE.yaml
after_success:
- docker login -e $DOCKER_EMAIL -u zma4580 -p $DOCKER_PASS || exit 1
- export REPO=zma4580/ftw
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT . || exit 1
- docker tag $REPO:$COMMIT $REPO:$TAG || exit 1
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER || exit 1
- docker push $REPO || exit 1
deploy:
- provider: pypi
  distributions: sdist
  user: techy
  password:
    secure: eg1McMGp0CftS92qMKWJeKyjWIBN+cTLMj1SDM/wEadzW7fGtV2/iVaEV4r0M4HZ2FF6h9Zi3PyuW/KPuwbff092oARFF+vmlRAH85v7DPLWctlnVUgAsEiA59aig2ImwFGu+NFPp3GPSgrzQqLHr43YJZhgo18U+TyAAEdxOE6KuQhHz+EgQQf7cG6BYyAoQE6DxvSfOAXvwFEx2A7JVh04aB2E0KJ1bTsAeVTwl4+xuhI9aVFBNCVxLM9+MsAKFbx1NbBIAMcKsgR7nkoJ0VG+lar9IrVXMXI7rh5DVX0dFO3axtuGaMgwTrizijcvddZ61Oq34eRfsrfa03lrG1+XB9TIPi9mrLFwMd4DRr+eXSlhUln735pOkrRHEWvqsf1KzGGDLD7quO1Mut0J7FmqYfKoIiUeXZ8ziv1hr3zFETudHga/wGr5VbeRKrK0MzWXQefPeCyboieBur0boOchhVOUAidRxguX78KP864zMhOT81ijxzkzD8wGxHuw/wKo7keA1tUq4KcB5hWnfX0h7nan5TQV5Wjv005SZbR90S4WiwXLvdvi36Ej0z6xb3SYBWG227X9BYkKESWcRxPF48hTEAl/ymNHRKyv7de+dT8FhSUKc2PCObaifW32mNNinPRPTM6kHwdy9pWIDsVSg8Vy18LqGYoHdQNM1Po=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  irc:
    channels:
    - secure: rUnggkHw6hYbjV8BHTebWCZxsblCMQtjPMYTe0aFUmjpsoziPXGfWMu3kxISgmMrog6vLcpomCcW68ysY3xcEHoY47U0tGEwtxwcHECht56cvqlT9TbUdhX7p+5RqNviHsAnuYBSxR42HXy535TWW8G6BmlkPcUfQKEdb8EgzUOJBvX8Z40FkBz6sMWzIluPdwBYcl3XthSpuVS8+891jvhHgtQTA2e8aXCeDXPPyrv9LSFKhT5/aNGvC6w8e+M74JFq5jeSGVI23i8OAhMyAKCzrCy2KoNd+azqTHwbpb9D/6tj9B0pGlaa2/ieefr8+fPm9JOPCLtG9BcnuCRpJ/nLgpnCy9pFoZsoECk4UwtQv4VwbEjiV9LK7xvjLBlE8r723tDtuopHgH+ob+dlMgGhEVUfl7T5Htxte2klMndNyaE6OFk6qcfnSnMPSWxtkUg/Dd23aGPxCI/sHikPiQQHKgT2Fz9ICafSzFC0cynpSZgG1c7TLugfS+RanMGnZLSjnL7xptYyuAI45XZpvV0LRd6L6gDBb9Mq+D9sZ11UrO+3zQqsDm6O2x6tPJuPs5oQIflevfovqKvpOZ5bWL4rZXWcnvIbxvfPuPKyslPY/ljkdGDCtXuAKPuE8k0e2DTF9LmJ+FRSWaPnsXyc/eyst2JYLzelZnoHXy8RTnw=
    template:
    - "%{repository} (%{commit}) : %{message} %{foo} "
    - 'Build details: %{build_url}'
env:
  global:
  - secure: d0nccFfy8Jqys5K/ya4pxr6lKfTd8fgFwB8UvxHYLqQqy4WO/I2CN/pJF9EVkXdpQq9JqBT6CVBntHlFhJgXjkwT6DfBlTEYZRRBimOfi8bVI7rL+R3JWnv5J4zJvGKFT7Pq3h18IeR5+6cDPIuV7TJt5DUlveqUVhrHIl32RxOJlUmgqlFWJZ0Qw9ngYbiQf9Q6ypojhpviCR4AlUMlG4gV0Q9hypW94Qq3FXnnQyYMyH/xZ+UcdDjZU/rMnz1djIToTZgHarzR7PH5OuNRSVIAXT3Ei8KdgGsn1tzIAL1tba9wa2tca72KHIJhMldC5FpHIIgeJoka569sbLMEtEDCkDQjPi4o2lbmnD8Az+9aRZiCnTl6inD8Ih7keS9S+iPF+8aOLhEXwRG9kjCjW6nX3gUAVQS5vzEp4AfzzWEcqJPeTU0htXOUV9yGVXpZLYuOSifGzMfmfMbcEBElVQzyIs/TkGtVtrG6r6NMdhM6tSHHMo7rjyKhSdDdXszNT2ZTd5kNQH1FFsn0S7RFQe+z8v3lzga3H5aBA3sEnuS1URsx38VNE0hgX3/XufLWuWI7hIt4374Q3NkdE427WugHfsKfeE7uLe2DHDQJikHqCqB2tpdKHNWvJ25Oiihrnb/VYZq2ZRoSKRVka52fTbcIqJju0hMnEjTuRn/x4LU=
  - secure: pjlL5RvSmSsLTCd7/GlGuoDAq9zdK3d+YH/BlPLmLOZuBKVEdwlxKNrEIEpL7yvOz0mPITTzP7jLvPz3smHIzArygmmHomVIv6bAVrJyli0eJNF2ZFQmcXFF2tECXMeocC/cGetXDjcRKr+s30IMwkmQhPCYs/Sftic0VMxcs9peo4qadB8U+onUV9YGYEn8IVbOHBuskp14xQqWvozy/cgrI9hbC+zuOdNMKZaoGzW5bO4Ai9oBqqPOOje6v8XDw6x2Yeqj5h4dnpoe2fW48pT8vax5UUKI8uW2fEyZDu6AMIlG5mxvlLK6gCSTZ/jSTRPF+w+tM907t8cCZe4j/Sr0eXHHCsjrGSYroD570nSjju88c92pNzM5qoHr3rF/L/29GF5Yp4AGhtJxaLUv3Tsc6WApA27IQa8QwmJYVgMBpybYfPiQM/6uk8eNHJoKlIrzBKjMefT0TVyucNxVcQPGclTFUnKpj58DYcyCFpzpoMyf44dghJOqaOfu6Q6Khvh080hooWUJuVZ3OeX4GL/cBDrZST09sxU5OaPJVm9ZcqCMrf0FPPLM8TPPEZn8fyr6F9kKizISWwMrG/EOBN+aADwcnYRqHezWKjQxfmv0YkS5bmk/wRPYqxKhK3ta9E4HSt7AEH3qT5WXSUc9ljb1JwQyUbqtx2AEexbArO8=
  - COMMIT=${TRAVIS_COMMIT::8}
